### ISSUE TITLE
Setting product's canonical URL

### ISSUE THREAD

**Issue by mcaquet** [thelia/thelia#1023]
In the product's SEO section, it would be useful to be able to set the canonical URL of the product page.

Currently, a different URL is generated for each language, and it's not possible to set the same URL for two different languages. 

Most of the time, we want to display the same canonical URL in every language.

Same request for categories and brands page.

**Comment by lunika** [comment]
Hi,

for SEO you need one canonical url per page because the content of your page is different when you switch between different language.

Maybe you have some resources explaining why it's better to have only one canonical URL.

**Comment by matdev** [comment]
When I switch language, Thelia doesn't change the page URL, it appends ?lang=en or ?lang=fr to the current URL.

Having a unique canonical URL would be consistent with this behavior, and it would enable tagging canonical page with <link rel="canonical" href="http://example.com/canonical-url"> so that google always displays the canonical URL in search results.
