### ISSUE TITLE
NULL in visible column prevent loop to return objects when visible='no'

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#2352]
When the "visible" checkbox is not checked for a product (or category, folder, etc.), a "NULL" is stored in the database instead of a 0

        $changeEvent = new ProductUpdateEvent($formData['id']);

        $changeEvent
            ...
            ->setVisible($formData['visible']) // $formData['visible'] is null if 'visible' checkbox is not checked.
            ...
        ;

But in the related loop, 1 or 0 is used to create the visibility filter : 

        $visible = $this->getVisible();

        if ($visible !== BooleanOrBothType::ANY) {
            $search->filterByVisible($visible ? 1 : 0);
        }

Thus, objects which have NULL in the `visible` column are not selected by the request if $visible is false.

See http://forum.thelia.net/viewtopic.php?id=12445 for original report.

What should we do ? Fix the controllers so that 0 is stored in the `visible` column, or fix the loops to consider NULL as false ?

**Comment by mbruchetpro** [comment]
After a few test, it seems that this issue is not issue anymore with Thelia v2.3.4.
Test with a product  
![screenshot](https://user-images.githubusercontent.com/36850920/36783350-08b43c98-1c7c-11e8-893b-24e408d5fadf.jpeg)
![capture d ecran 2018-02-28 a 11 38 11](https://user-images.githubusercontent.com/36850920/36783399-2a55cc2c-1c7c-11e8-9707-4240560ed3b1.png)
![screenshot 1](https://user-images.githubusercontent.com/36850920/36783425-399b7e3e-1c7c-11e8-912b-7c8cc7a48fae.jpeg)
![capture d ecran 2018-02-28 a 11 40 34](https://user-images.githubusercontent.com/36850920/36783440-46fe88c8-1c7c-11e8-9eb0-bda67793e815.png)

**Comment by roadster31** [comment]
Fine !
