### ISSUE TITLE
Changing the name of VirtualProductControl breaks the back-office.

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#937]
Steps to reproduce : 
1. Rename `VirtualProductControl` as `VirtualProductControl.BAK`
2. Load the back-office -> `ServiceNotFoundException: You have requested a non-existent service "virtualproductcontrol.hook".`
3. Rename `VirtualProductControl.BAK` as `VirtualProductControl.`
4. Load the back-office again -> `ServiceNotFoundException: You have requested a non-existent service "virtualproductcontrol.hook".`. **Augh !**

The only way to restore a normal situation is to delete manually the cache directories.

**Comment by vincentwinkel** [comment]
Hi,
I usually work with Magento2. I guess you know how it is complex to develop using this CMS. So I consider I'm not the "average developer" that you're talking about. However, I created a Thelia 2.2.1 project via Git, and after the deployment on my Test server, I imported my modules/, template/design/ and media/ folders, exactly like I did on my local. I also imported my database. But, I don't know why, I finally got this error:
You have requested a non-existent service "backofficecss.css_render_hook".
Rights (chmod/chown) are ok, cache is empty, module and hook are ok... But I don't know how to remove this error.

In my opinion, saying "if the average developer destroys his project, he is the only one responsible" is only acceptable when there have some docs explaining how to avoid that. Thelia2 has no docs (I mean a real dev doc, not 4 lines explaining how to use composer) and no community.
As developers, it doesn't matter if we are an expert or a neophyte. When we get an error, we don't want to spent 3 days to vainly debug just because you're too lazy to write a doc or to add an exception.
It's maybe not a bug itself, but the missing prevention is a bug.

**Comment by roadster31** [comment]
Please report you problem to the forum (aka, the community) http://forum.thelia.net/, which is usually very reactive.
You may also read the documentation here: http://doc.thelia.net . As far as I can read, you'll find there more than 3 lines about composer.

**Comment by vincentwinkel** [comment]
This doc is no so bad but it's, in my opinion, a simple listing of ressources (listing of modules, hooks, events, etc) but it doesn't explain how to use those ressources.
For instance, about the above explanation of the containerBuilder processing, where I can find this info in the doc ? Where is the doc explaining how the pages are built ? (templates, blocks, cache, assets, etc). There are only some pieces of info here and there but you seem forget that we (lambda developers) are not necessarily Thelia-dedicated. You made it so you know exactly how it works, but not us. And your challenge, in addition to create Thelia, is to give us enough doc and motivation to adopt your tool. 

Github is not the right place to discuss about that and I apologize because Thelia stays a good and promising project. But since I read your answers in forums, etc (since at least 2 years) I'm a bit bored to see you saying like "we make a tool, if you follow the rules, the tool will work, otherwise learn them by yourself".
Good continuation anyway !

**Comment by roadster31** [comment]
Sorry to be so boring.

Have fun with Magento 2

**Comment by Asenar** [comment]
@vincentwinkel , 
I think you used this module : https://github.com/thelia-modules/BackOfficeCss (compatible for Thelia 2.1 ).

Maybe this can help : http://forum.thelia.net/viewtopic.php?id=11723

**Comment by vincentwinkel** [comment]
Asenar, I think the problem is not from the code but from the config. I have a Thelia 2.2.1 website called A with a modules/ folder (including custom an from community modules) and my design/ folder.
I created a new Thelia 2.2.1 project B from scratch git-based, imported modules/ and design/ (+ others) folders from A and everything work correctly, using Docker. Now, I pull this project B on another server with the same database, without Docker, but I get the error above. I will try again this evening and I come back to this topic if needed.


roadster31, I didn't answered to this topic because of my issue but because I saw the comment above following (like usually) mentality "Thelia is what it is, like it or go out". I enjoyed that to ask you to be more comprehensive with us. And (like usually) your answer is totally inappropriate.


Thanks everyone
